services:
  ocr-service:
    build: .
    shm_size: "8gb"
    ports:
      - "18010:8000"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      OCR_TMP_DIR: /data/tmp
      OCR_OUT_DIR: /data/out
      OCR_LANG: spa
      OCR_MODE: searchable_cpu
      REVIEW_APP_VERSION: "1.2"
      CLASSIFY_DIR: /data/classify
      CLASSIFY_CONF_THRESHOLD: "0.99"
      STAMP_MODEL_PATH: /data/models/stamp_detector_v2.pt
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    volumes:
      - ./data:/data
      - ./app:/app/app
      - ./scripts:/app/scripts:ro
    networks:
      - grh_network

networks:
  grh_network:
    external: true
