apiVersion: v1
kind: Service
metadata:
  name: ocr-search-api
  namespace: ocr-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ocr-search-api
  ports:
    - name: http
      port: 8000
      targetPort: http
