apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ocr-data
  namespace: ocr-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn
