apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ocr-shared-cache
  namespace: ocr-service
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-storage
